version: "3.7"

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: funds
      POSTGRES_PASSWORD: funds_pw
    ports:
      - "5432:5432"
    volumes:
      - funds-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - funds-redis:/var/lib/redis/data

  funds:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./funds
        target: /opt/app/funds
    ports:
      - "8010:8010"
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./funds
        target: /opt/app/funds
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - funds
    ports:
      - "8020:8020"

volumes:
  funds-postgres:
  funds-redis:
